steps:
  - name: 'node:8.9'
    args: [ 'npm', 'install', '--unsafe-perm' ]
  - name: 'node:8.9'
    env:
      - 'AUTH0_AUDIENCE=https://d.api.dungeon.studio'
      - 'API_HOST=d.api.dungeon.studio'
    args: [ 'npm', 'run', 'build' ]
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'rsync', '-r', '-d', 'dist/', 'gs://d.my.dungeon.studio/' ]
